server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    employees: DEBUG
    org.hibernate.SQL: TRACE

employees:
  backend-url: http://localhost:8081

resilience4j:
  circuitbreaker:
    instances:
      clientCircuitBreaker:
        slidingWindowSize: 3
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: count_based
        waitDurationInOpenState: 60s
        failureRateThreshold: 50
  timelimiter:
    instances:
      clientTimeLimiter:
        timeout-duration: 1s
  retry:
    instances:
      clientRetry:
        max-attempts: 3
  bulkhead:
    instances:
      clientBulkhead:
        max-concurrent-calls: 5
        max-wait-duration: 10s
  ratelimiter:
    instances:
      clientRateLimiter:
        limit-refresh-period: 1s
        limit-for-period: 5
        timeout-duration: 10s
        subscribe-for-events: true
