server:
  port: 8000

spring:
  application:
    name: gateway
  cloud:
    gateway:
#      filter:
#        local-response-cache:
#          enabled: true
      routes:
        - id: employees-backend
#          uri: http://localhost:8081
          uri: lb://employees-backend
          predicates:
            - Path=/api/employees/**
          filters:
            - AddRequestHeader=X-Gateway, Hello
            - name: CircuitBreaker
              args:
                name: employees-backend
                fallbackUri: forward:/api/dummy-employees
            - name: Retry
              args:
                retries: 3
#            - LocalResponseCache=30m,500MB


resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 30s
    instances:
      employees-backend:
        baseConfig: default
  timelimiter:
    configs:
      default:
        timeout-duration: 5s

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0

eureka:
  instance:
    prefer-ip-address: true